package com.peterwolf.forestfire.fire.incident;

public enum IncidentMarkerType {
	FIRE_FRONT,
	SPOT_FIRE,
	WATER_SOURCE,
	PUMP_LOCATION,
	COMMAND_POST,
	EVACUATION_POINT,
	DANGER_ZONE,
	ESCAPE_ROUTE,
	STRUCTURE_PROTECTION,
	RESCUE_REQUIRED
}
